<a href="https://colab.research.google.com/github/asmita-mukherjee/StepWise-Pytorch/blob/main/Understandig_torch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tuitorial : https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

In [1]:
import torch

In [25]:
a = torch.tensor([2.,3.],requires_grad=True)

In [26]:
a.shape

torch.Size([2])

In [27]:
b = torch.tensor([6., 4.], requires_grad=True)

In [28]:
Q = 3*a**3 - b**2

In [29]:
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

Calculate gradient of Q, but we pass dq/dq , which acts a scaling parameter

In [30]:
Q.backward(gradient = torch.tensor([1.,1.])) # doesnt return anything, stores the gradient of each parameter in its respect .grad argument 

In [31]:
a.grad #

tensor([36., 81.])

In [32]:
9*a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

In [33]:
b.grad

tensor([-12.,  -8.])

In [34]:
-2*b

tensor([-12.,  -8.], grad_fn=<MulBackward0>)

for ex if you supplied gradient [1,2] it would scale the a's grad by 1 and b's grad by 2

In [39]:
a.grad = None

In [40]:
b.grad = None

In [42]:
Q.grad = None

In [48]:
Q = 3*a**3 - b**2

In [49]:
Q.backward(gradient=torch.tensor([1.,2.]))

In [50]:
a.grad

tensor([ 36., 162.])

In [51]:
b.grad

tensor([-12., -16.])

In [52]:
9*a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

Checking multiple layers of backprop

In [53]:
p = torch.tensor([1.,2.],requires_grad=True)
q = torch.tensor([3.,4.],requires_grad=True)

In [54]:
r = 3*p**3 + 2*q**2
s = 4*p**2
t = 2*r + 3*s

In [56]:
t.backward(gradient=torch.tensor([1.,1.]))

In [58]:
s.grad

<ipython-input-58-3fc1f65f0159>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)
  s.grad


In [61]:
p.grad # hence stores dt/dp

tensor([ 42., 120.])

In [62]:
q.grad # hence stores dt/dq

tensor([24., 32.])